language: python
python:
  - "3.6"
install:
  - ./install_xapian.sh
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
before_script:
  - python manage.py migrate

script:
  - python manage.py test
  
